#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Reads CloudFormation outputs from the AirflowEcsExecutorTest stack
# and generates a Breeze-compatible env file.
#
# Usage:
#   ./generate_breeze_env.sh                    # real AWS
#   AWS_ENDPOINT_URL=http://localhost:4566 ./generate_breeze_env.sh  # LocalStack
#
set -euo pipefail

STACK_NAME="AirflowEcsExecutorTest"
ENDPOINT_FLAG=""
if [[ -n "${AWS_ENDPOINT_URL:-}" ]]; then
    ENDPOINT_FLAG="--endpoint-url ${AWS_ENDPOINT_URL}"
fi

echo "Reading outputs from stack: ${STACK_NAME}..."

get_output() {
    local key="$1"
    aws cloudformation describe-stacks \
        --stack-name "${STACK_NAME}" \
        ${ENDPOINT_FLAG} \
        --query "Stacks[0].Outputs[?OutputKey=='${key}'].OutputValue" \
        --output text
}

ALPHA_CLUSTER=$(get_output "AlphaClusterName")
ALPHA_TASK_DEF=$(get_output "AlphaTaskDefArn")
ALPHA_SG=$(get_output "AlphaSecurityGroupId")
BETA_CLUSTER=$(get_output "BetaClusterName")
BETA_TASK_DEF=$(get_output "BetaTaskDefArn")
BETA_SG=$(get_output "BetaSecurityGroupId")
SUBNETS=$(get_output "SubnetIds")
DB_ENDPOINT=$(get_output "DbEndpoint")
DB_PORT=$(get_output "DbPort")
DB_SECRET_ARN=$(get_output "DbSecretArn")
LOG_BUCKET=$(get_output "LogBucketName")
ECR_REPO=$(get_output "EcrRepoUri")
REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")

# Resolve DB password from Secrets Manager
DB_PASSWORD=""
if [[ "${DB_SECRET_ARN}" != "N/A" ]]; then
    DB_SECRET_JSON=$(aws secretsmanager get-secret-value \
        --secret-id "${DB_SECRET_ARN}" \
        ${ENDPOINT_FLAG} \
        --query "SecretString" --output text)
    DB_PASSWORD=$(echo "${DB_SECRET_JSON}" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")
fi

DB_CONN="postgresql+psycopg2://airflow:${DB_PASSWORD}@${DB_ENDPOINT}:${DB_PORT}/airflow_db"

OUTPUT_FILE="breeze_ecs_env.sh"

cat > "${OUTPUT_FILE}" <<EOF
#!/usr/bin/env bash
# Auto-generated by generate_breeze_env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Copy to: files/airflow-breeze-config/init.sh (auto-sourced by Breeze)

echo "=== Loading multi-team ECS executor config (from CDK stack) ==="

# --- Multi-team mode ---
export AIRFLOW__CORE__MULTI_TEAM=True
export AIRFLOW__CORE__LOAD_EXAMPLES=False

# --- Database (RDS PostgreSQL) ---
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="${DB_CONN}"

# --- Executor: global=Local, team_alpha=ECS, team_beta=ECS ---
export AIRFLOW__CORE__EXECUTOR="LocalExecutor;team_alpha=airflow.providers.amazon.aws.executors.ecs.ecs_executor.AwsEcsExecutor;team_beta=airflow.providers.amazon.aws.executors.ecs.ecs_executor.AwsEcsExecutor"

# --- DAG bundle config (team-associated bundles) ---
export AIRFLOW__DAG_PROCESSOR__DAG_BUNDLE_CONFIG_LIST='[
  {"name":"team_alpha_dags","classpath":"airflow.dag_processing.bundles.local.LocalDagBundle","kwargs":{"path":"/opt/airflow/dags/team_alpha"},"team_name":"team_alpha"},
  {"name":"team_beta_dags","classpath":"airflow.dag_processing.bundles.local.LocalDagBundle","kwargs":{"path":"/opt/airflow/dags/team_beta"},"team_name":"team_beta"},
  {"name":"shared_dags","classpath":"airflow.dag_processing.bundles.local.LocalDagBundle","kwargs":{"path":"/opt/airflow/dags/shared"}}
]'

# --- team_alpha ECS config ---
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__CLUSTER="${ALPHA_CLUSTER}"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__CONTAINER_NAME="airflow-worker"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__TASK_DEFINITION="${ALPHA_TASK_DEF}"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__LAUNCH_TYPE="FARGATE"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__PLATFORM_VERSION="LATEST"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__ASSIGN_PUBLIC_IP="True"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__SECURITY_GROUPS="${ALPHA_SG}"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__SUBNETS="${SUBNETS}"
export AIRFLOW__TEAM_ALPHA___AWS_ECS_EXECUTOR__REGION_NAME="${REGION}"

# --- team_beta ECS config ---
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__CLUSTER="${BETA_CLUSTER}"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__CONTAINER_NAME="airflow-worker"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__TASK_DEFINITION="${BETA_TASK_DEF}"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__LAUNCH_TYPE="FARGATE"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__PLATFORM_VERSION="LATEST"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__ASSIGN_PUBLIC_IP="True"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__SECURITY_GROUPS="${BETA_SG}"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__SUBNETS="${SUBNETS}"
export AIRFLOW__TEAM_BETA___AWS_ECS_EXECUTOR__REGION_NAME="${REGION}"

# --- Remote logging (S3) ---
export AIRFLOW__LOGGING__REMOTE_LOGGING="True"
export AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER="s3://${LOG_BUCKET}/logs"
export AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID="aws_default"

echo "=== Config loaded (alpha=${ALPHA_CLUSTER}, beta=${BETA_CLUSTER}) ==="

# --- References (not exported, just for humans) ---
# ECR repo: ${ECR_REPO}
# DB secret ARN: ${DB_SECRET_ARN}
# DB endpoint: ${DB_ENDPOINT}:${DB_PORT}
EOF

echo "Generated ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  1. Build & push your Airflow worker image:"
echo "     docker build -t ${ECR_REPO}:latest -f <your-Dockerfile> ."
echo "     aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_REPO%%/*}"
echo "     docker push ${ECR_REPO}:latest"
echo ""
echo "  2. Copy env vars into Breeze:"
echo "     cp ${OUTPUT_FILE} ../../files/airflow-breeze-config/init.sh"
echo "     # Or: source ${OUTPUT_FILE} inside Breeze"
echo ""
echo "  3. Start Breeze with AWS credentials:"
echo "     breeze --forward-credentials"
